In [2]:
import pandas as pd
import numpy as np

In [4]:
hw = pd.read_csv("../Dataset/height-weight.csv")
hw

    Weight  Height
0       45     120
1       58     135
2       48     123
3       60     145
4       70     160
5       78     162
6       80     163
7       90     175
8       95     182
9       78     170
10      82     176
11      95     182
12     105     175
13     100     183
14      85     170
15      78     177
16      50     140
17      65     159
18      76     150
19      87     167
20      45     129
21      56     140
22      72     160

In [6]:
weight_mean = hw["Weight"].mean()
weight_mean

73.82608695652173

In [8]:
height_mean = hw["Height"].mean()
height_mean

158.3913043478261

In [10]:
hw["weight-mean(w)"] = hw["Weight"] - weight_mean
hw

    Weight  Height  weight-mean(w)
0       45     120      -28.826087
1       58     135      -15.826087
2       48     123      -25.826087
3       60     145      -13.826087
4       70     160       -3.826087
5       78     162        4.173913
6       80     163        6.173913
7       90     175       16.173913
8       95     182       21.173913
9       78     170        4.173913
10      82     176        8.173913
11      95     182       21.173913
12     105     175       31.173913
13     100     183       26.173913
14      85     170       11.173913
15      78     177        4.173913
16      50     140      -23.826087
17      65     159       -8.826087
18      76     150        2.173913
19      87     167       13.173913
20      45     129      -28.826087
21      56     140      -17.826087
22      72     160       -1.826087

In [11]:
hw["height-mean(h)"] = hw["Height"] - height_mean
hw

    Weight  Height  weight-mean(w)  height-mean(h)
0       45     120      -28.826087      -38.391304
1       58     135      -15.826087      -23.391304
2       48     123      -25.826087      -35.391304
3       60     145      -13.826087      -13.391304
4       70     160       -3.826087        1.608696
5       78     162        4.173913        3.608696
6       80     163        6.173913        4.608696
7       90     175       16.173913       16.608696
8       95     182       21.173913       23.608696
9       78     170        4.173913       11.608696
10      82     176        8.173913       17.608696
11      95     182       21.173913       23.608696
12     105     175       31.173913       16.608696
13     100     183       26.173913       24.608696
14      85     170       11.173913       11.608696
15      78     177        4.173913       18.608696
16      50     140      -23.826087      -18.391304
17      65     159       -8.826087        0.608696
18      76     150        2.173913       -8.391304
19      87     167       13.173913        8.608696
20      45     129      -28.826087      -29.391304
21      56     140      -17.826087      -18.391304
22      72     160       -1.826087        1.608696

In [13]:
hw["weight-mean(w)-square"] = hw["weight-mean(w)"] * hw["weight-mean(w)"]
hw

    Weight  Height  weight-mean(w)  height-mean(h)  weight-mean(w)-square
0       45     120      -28.826087      -38.391304             830.943289
1       58     135      -15.826087      -23.391304             250.465028
2       48     123      -25.826087      -35.391304             666.986767
3       60     145      -13.826087      -13.391304             191.160681
4       70     160       -3.826087        1.608696              14.638941
5       78     162        4.173913        3.608696              17.421550
6       80     163        6.173913        4.608696              38.117202
7       90     175       16.173913       16.608696             261.595463
8       95     182       21.173913       23.608696             448.334594
9       78     170        4.173913       11.608696              17.421550
10      82     176        8.173913       17.608696              66.812854
11      95     182       21.173913       23.608696             448.334594
12     105     175       31.173913       16.608696             971.812854
13     100     183       26.173913       24.608696             685.073724
14      85     170       11.173913       11.608696             124.856333
15      78     177        4.173913       18.608696              17.421550
16      50     140      -23.826087      -18.391304             567.682420
17      65     159       -8.826087        0.608696              77.899811
18      76     150        2.173913       -8.391304               4.725898
19      87     167       13.173913        8.608696             173.551985
20      45     129      -28.826087      -29.391304             830.943289
21      56     140      -17.826087      -18.391304             317.769376
22      72     160       -1.826087        1.608696               3.334594

In [14]:
hw['Height-weight-mul'] = hw['height-mean(h)'] * hw['weight-mean(w)']
hw

,Weight,Height,weight-mean(w),height-mean(h),weight-mean(w)-square,Height-weight-mul
0,45,120,-28.826087,-38.391304,830.943289,1106.671078
1,58,135,-15.826087,-23.391304,250.465028,370.192817
2,48,123,-25.826087,-35.391304,666.986767,914.018904
3,60,145,-13.826087,-13.391304,191.160681,185.149338
4,70,160,-3.826087,1.608696,14.638941,-6.155009
5,78,162,4.173913,3.608696,17.421550,15.062382
6,80,163,6.173913,4.608696,38.117202,28.453686
7,90,175,16.173913,16.608696,261.595463,268.627599
8,95,182,21.173913,23.608696,448.334594,499.888469
9,78,170,4.173913,11.608696,17.421550,48.453686
10,82,176,8.173913,17.608696,66.812854,143.931947
11,95,182,21.173913,23.608696,448.334594,499.888469
12,105,175,31.173913,16.608696,971.812854,517.758034
13,100,183,26.173913,24.608696,685.073724,644.105860
14,85,170,11.173913,11.608696,124.856333,129.714556
15,78,177,4.173913,18.608696,17.421550,77.671078
16,50,140,-23.826087,-18.391304,567.682420,438.192817
17,65,159,-8.826087,0.608696,77.899811,-5.372401
18,76,150,2.173913,-8.391304,4.725898,-18.241966
19,87,167,13.173913,8.608696,173.551985,113.410208
20,45,129,-28.826087,-29.391304,830.943289,847.236295
21,56,140,-17.826087,-18.391304,317.769376,327.844991
22,72,160,-1.826087,1.608696,3.334594,-2.937618

In [16]:
sum_mul = hw['Height-weight-mul'].sum()
sum_mul

7143.565217391304

In [18]:
sum_square = hw['weight-mean(w)-square'].sum()
sum_square

7027.304347826087

In [20]:
b1 = sum_mul/sum_square
b1

1.01654416314005

In [22]:
b0 = height_mean + (b1*weight_mean)
b0

233.43878213094803

In [24]:
hw['y cap']= b0 + (b1*hw['Weight'])
hw

,Weight,Height,weight-mean(w),height-mean(h),weight-mean(w)-square,Height-weight-mul,y cap
0,45,120,-28.826087,-38.391304,830.943289,1106.671078,279.183269
1,58,135,-15.826087,-23.391304,250.465028,370.192817,292.398344
2,48,123,-25.826087,-35.391304,666.986767,914.018904,282.232902
3,60,145,-13.826087,-13.391304,191.160681,185.149338,294.431432
4,70,160,-3.826087,1.608696,14.638941,-6.155009,304.596874
5,78,162,4.173913,3.608696,17.421550,15.062382,312.729227
6,80,163,6.173913,4.608696,38.117202,28.453686,314.762315
7,90,175,16.173913,16.608696,261.595463,268.627599,324.927757
8,95,182,21.173913,23.608696,448.334594,499.888469,330.010478
9,78,170,4.173913,11.608696,17.421550,48.453686,312.729227
10,82,176,8.173913,17.608696,66.812854,143.931947,316.795404
11,95,182,21.173913,23.608696,448.334594,499.888469,330.010478
12,105,175,31.173913,16.608696,971.812854,517.758034,340.175919
13,100,183,26.173913,24.608696,685.073724,644.105860,335.093198
14,85,170,11.173913,11.608696,124.856333,129.714556,319.845036
15,78,177,4.173913,18.608696,17.421550,77.671078,312.729227
16,50,140,-23.826087,-18.391304,567.682420,438.192817,284.265990
17,65,159,-8.826087,0.608696,77.899811,-5.372401,299.514153
18,76,150,2.173913,-8.391304,4.725898,-18.241966,310.696139
19,87,167,13.173913,8.608696,173.551985,113.410208,321.878124
20,45,129,-28.826087,-29.391304,830.943289,847.236295,279.183269
21,56,140,-17.826087,-18.391304,317.769376,327.844991,290.365255
22,72,160,-1.826087,1.608696,3.334594,-2.937618,306.629962